version: 0.2

phases:
  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/1.5.3/terraform_1.5.3_linux_amd64.zip"
      - "unzip terraform_1.5.3_linux_amd64.zip"
      - "mv terraform /usr/local/bin"
  initialize:
    commands:
      - terraform init
  plan:
    commands:
      - terraform plan
  apply:
    commands:
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo terraform $TF_COMMAND completed on ´date´
